include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # doc-style related: https://dart.dev/guides/language/effective-dart/documentation
    - package_api_docs
    - public_member_api_docs
    - comment_references
    - slash_for_doc_comments
    # pub related: https://dart.dev/tools/linter-rules#pub-rules
    - depend_on_referenced_packages
    - secure_pubspec_urls
    # import related
    - always_use_package_imports
    - implementation_imports
